### ISSUE TITLE
B2BAuraTemplateEnabled in b2b scratch org setting is invalid

### ISSUE THREAD

**Issue by syunyama** [forcedotcom/commerce-on-lightning#160]
When I ran commando below:
```
sfdx commerce:scratchorg:create -t b2b -a sampleB2BScratch -u "$RANDOM@1commerce.com" -v DevHub -w 15
```

 I got error
```
ERROR running commerce:scratchorg:create:  {
    "status": 1,
    "name": "INVALID_INPUT",
    "message": "B2BAuraTemplateEnabled は有効な機能値ではありません。",
    "exitCode": 1,
    "commandName": "OrgCreateCommand",
    "stack": "INVALID_INPUT: B2BAuraTemplateEnabled は有効な機能値ではありません。\n    at HttpApi.getError (/usr/local/lib/sfdx/node_modules/jsforce/lib/http-api.js:250:13)\n    at /usr/local/lib/sfdx/node_modules/jsforce/lib/http-api.js:95:22\n    at tryCallOne (/usr/local/lib/sfdx/node_modules/promise/lib/core.js:37:12)\n    at /usr/local/lib/sfdx/node_modules/promise/lib/core.js:123:15\n    at flush (/usr/local/lib/sfdx/node_modules/asap/raw.js:50:29)\n    at processTicksAndRejections (internal/process/task_queues.js:77:11)\nOuter stack:\n    at Function.wrap (/usr/local/lib/sfdx/node_modules/@salesforce/core/lib/sfdxError.js:171:27)\n    at OrgCreateCommand.catch (/usr/local/lib/sfdx/node_modules/@salesforce/command/lib/sfdxCommand.js:248:67)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at OrgCreateCommand._run (/usr/local/lib/sfdx/node_modules/@salesforce/command/lib/sfdxCommand.js:85:13)\n    at Config.runCommand (/usr/local/lib/sfdx/node_modules/@oclif/config/lib/config.js:173:24)\n    at SfdxMain.run (/usr/local/lib/sfdx/node_modules/@oclif/command/lib/main.js:27:9)\n    at SfdxMain._run (/usr/local/lib/sfdx/node_modules/@oclif/command/lib/command.js:43:20)\n    at Object.run (/usr/local/lib/sfdx/dist/cli.js:162:47)",
    "warnings": [],
    "command": "sfdx force:org:create --targetdevhubusername=\"*********\" --definitionfile=/Users/*********/.commerce/config/b2b-project-scratch-def.json --setalias=\"sampleB2BScratch\" --durationdays=30 --wait=15 username=\"11220@1commerce.com\" --setdefaultusername --json --apiversion=56.0"
}
```

**Comment by syunyama** [comment]
It was working correctly if I remove `B2BAuraTemplateEnabled` from `b2b-project-scratch-def.json` and `both-project-scratch-def.json`.

**Comment by joeluong-sfcc** [comment]
@syunyama Could you provide what version of core you're using? `B2BAuraTemplateEnabled` was added in 242 and will most likely not work with previous versions

**Comment by syunyama** [comment]
@joeluong-sfcc 
I was on v56 and understood I should use v57.
I will close this ticket.
