### ISSUE TITLE
Getting "The requested resource does not exist" when using sfdx commerce:store:create --store-name teststore -u testCC

### ISSUE THREAD

**Issue by lucam75** [forcedotcom/commerce-on-lightning#282]
I'm having the below problem when running `sfdx commerce:store:create --store-name teststore -u testCC` 

```
ERROR running StoreQuickstartSetup:  {
    "code": 1,
    "context": "Create",
    "commandName": "Create",
    "message": "The requested resource does not exist",
    "name": "NOT_FOUND",
    "status": 1,
    "stack": "NOT_FOUND: The requested resource does not exist\n    at HttpApi.getError (/opt/homebrew/lib/node_modules/@salesforce/cli/node_modules/jsforce/lib/http-api.js:252:12)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /opt/homebrew/lib/node_modules/@salesforce/cli/node_modules/jsforce/lib/http-api.js:122:23\n    at async Connection.create (/opt/homebrew/lib/node_modules/@salesforce/cli/node_modules/jsforce/lib/connection.js:796:133)\n    at async Create.run (/opt/homebrew/lib/node_modules/@salesforce/cli/node_modules/@salesforce/plugin-data/lib/commands/data/create/record.js:23:24)\n    at async Create._run (/opt/homebrew/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/command.js:117:22)\n    at async Config.runCommand (/opt/homebrew/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/config/config.js:314:25)\n    at async run (/opt/homebrew/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/main.js:89:16)",
    "exitCode": 1,
    "warnings": [
        "The \"-u\" flag has been deprecated. Use \"--target-org | -o\" instead.",
        "The \"--apiversion\" flag has been deprecated. Use \"--api-version\" instead."
    ],
    "command": "sfdx force:data:record:create -u \"lusername@company.com\" -s \"ShippingConfigurationSet\" -v \"TargetRecordId=0ZE8G0000008aRyWAI\" --json --apiversion=59.0"
}
ERROR running commerce:store:create:  StoreQuickstartSetup failed
```

Running in isolation the failed command responds with the same error.

I'm running this in my local environment over the `develop` branch.

**Comment by mishapapash** [comment]
The same case((((

**Comment by ihor-shchepilov** [comment]
I have the same issue...

**Comment by ViraOsinaCT** [comment]
Same for me:
SFDX CLI Version: @salesforce/cli/2.23.20 darwin-x64 node-v20.10.0
@salesforce/commerce@248.1.3

**Comment by ViraOsinaCT** [comment]
@tarcang I've tried creating a store with @salesforce/commerce@250.1.0 as suggested. It does not show an error that ShippingConfigurationSet does not exist, but the object itself is missing:

"code": 1,
  "context": "DataSoqlQueryCommand",
  "commandName": "DataSoqlQueryCommand",
  "message": "\nSELECT Id FROM ShippingConfigurationSet\n               ^\nERROR at Row:1:Column:16\nsObject type 'ShippingConfigurationSet' is not supported. If you are attempting to use a custom object, be sure to append the '__c' after the entity name. Please reference your WSDL or the describe call for the appropriate names."
  
  Moreover, 250.1.0 triggers another error: 
  _### {
  "status": 1,
  "name": "SfdxError",
  "message": "{\n    \"code\": 1,\n    \"context\": \"Create\",\n    \"commandName\": \"Create\",\n    \"message\": \"The requested resource does not exist\",\n    \"name\": \"NOT_FOUND\",\n    \"status\": 1,\n    \"stack\": \"NOT_FOUND: The requested resource does not exist\\n    at HttpApi.getError (/usr/local/lib/sf/node_modules/jsforce/lib/http-api.js:252:12)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async /usr/local/lib/sf/node_modules/jsforce/lib/http-api.js:122:23\\n    at async Connection.create (/usr/local/lib/sf/node_modules/jsforce/lib/connection.js:799:133)\\n    at async Create.run (/usr/local/lib/sf/node_modules/@salesforce/plugin-data/lib/commands/data/create/record.js:23:24)\\n    at async Create._run (/usr/local/lib/sf/node_modules/@salesforce/plugin-data/node_modules/@oclif/core/lib/command.js:117:22)\\n    at async Config.runCommand (/usr/local/lib/sf/node_modules/@oclif/core/lib/config/config.js:529:25)\\n    at async run (/usr/local/lib/sf/node_modules/@oclif/core/lib/main.js:90:16)\",\n    \"exitCode\": 1,\n    \"warnings\": [\n        \"The \\\"-u\\\" flag has been deprecated. Use \\\"--target-org | -o\\\" instead.\",\n        \"The \\\"--apiversion\\\" flag has been deprecated. Use \\\"--api-version\\\" instead.\"\n    ],\n    \"command\": \"sfdx force:data:record:create -u \\\"test_b2с@test.com\\\" -s \\\"ShippingConfigurationSet\\\" -v \\\"TargetRecordId=0ZEJX000002zQkP4AU\\\" --json --apiversion=59.0\"\n}",
  "exitCode": 1,
  "commandName": "StoreQuickstartSetup",
  "stack": "SfdxError: {\n    \"code\": 1,\n    \"context\": \"Create\",\n    \"commandName\": \"Create\",\n    \"message\": \"The requested resource does not exist\",\n    \"name\": \"NOT_FOUND\",\n    \"status\": 1,\n    \"stack\": \"NOT_FOUND: The requested resource does not exist\\n    at HttpApi.getError (/usr/local/lib/sf/node_modules/jsforce/lib/http-api.js:252:12)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async /usr/local/lib/sf/node_modules/jsforce/lib/http-api.js:122:23\\n    at async Connection.create (/usr/local/lib/sf/node_modules/jsforce/lib/connection.js:799:133)\\n    at async Create.run (/usr/local/lib/sf/node_modules/@salesforce/plugin-data/lib/commands/data/create/record.js:23:24)\\n    at async Create._run (/usr/local/lib/sf/node_modules/@salesforce/plugin-data/node_modules/@oclif/core/lib/command.js:117:22)\\n    at async Config.runCommand (/usr/local/lib/sf/node_modules/@oclif/core/lib/config/config.js:529:25)\\n    at async run (/usr/local/lib/sf/node_modules/@oclif/core/lib/main.js:90:16)\",\n    \"exitCode\": 1,\n    \"warnings\": [\n        \"The \\\"-u\\\" flag has been deprecated. Use \\\"--target-org | -o\\\" instead.\",\n        \"The \\\"--apiversion\\\" flag has been deprecated. Use \\\"--api-version\\\" instead.\"\n    ],\n    \"command\": \"sfdx force:data:record:create -u \\\"test_b2с@test.com\\\" -s \\\"ShippingConfigurationSet\\\" -v \\\"TargetRecordId=0ZEJX000002zQkP4AU\\\" --json --apiversion=59.0\"\n}\n    at shellJsonSfdx (/Users/viraosina/.local/share/sf/node_modules/@salesforce/commerce/lib/lib/utils/shell.js:111:23)\n    at forceDataRecordCreate (/Users/viraosina/.local/share/sf/node_modules/@salesforce/commerce/lib/lib/utils/sfdx/forceDataSoql.js:33:42)\n    at StoreQuickstartSetup.initShipping (/Users/viraosina/.local/share/sf/node_modules/@salesforce/commerce/lib/commands/commerce/store/quickstart/setup.js:306:51)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async StoreQuickstartSetup.run (/Users/viraosina/.local/share/sf/node_modules/@salesforce/commerce/lib/commands/commerce/store/quickstart/setup.js:116:9)\n    at async StoreQuickstartSetup._run (/Users/viraosina/.local/share/sf/node_modules/@salesforce/command/lib/sfdxCommand.js:81:40)\n    at async StoreCreate.pushStoreSources (/Users/viraosina/.local/share/sf/node_modules/@salesforce/commerce/lib/commands/commerce/store/create.js:259:21)\n    at async StoreCreate.run (/Users/viraosina/.local/share/sf/node_modules/@salesforce/commerce/lib/commands/commerce/store/create.js:180:9)\n    at async StoreCreate._run (/Users/viraosina/.local/share/sf/node_modules/@salesforce/command/lib/sfdxCommand.js:81:40)\n    at async Config.runCommand (/Users/viraosina/.local/share/sf/client/2.23.20-50cd2d8/node_modules/@oclif/core/lib/config/config.js:417:25)",
  "warnings": []
}
{
  "status": 1,
  "name": "SfdxError",
  "message": "StoreQuickstartSetup failed",
  "exitCode": 1,
  "commandName": "StoreCreate",
  "stack": "SfdxError: StoreQuickstartSetup failed\n    at StoreCreate.pushStoreSources (/Users/viraosina/.local/share/sf/node_modules/@salesforce/commerce/lib/commands/commerce/store/create.js:261:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async StoreCreate.run (/Users/viraosina/.local/share/sf/node_modules/@salesforce/commerce/lib/commands/commerce/store/create.js:180:9)\n    at async StoreCreate._run (/Users/viraosina/.local/share/sf/node_modules/@salesforce/command/lib/sfdxCommand.js:81:40)\n    at async Config.runCommand (/Users/viraosina/.local/share/sf/client/2.23.20-50cd2d8/node_modules/@oclif/core/lib/config/config.js:417:25)\n    at async run (/Users/viraosina/.local/share/sf/client/2.23.20-50cd2d8/node_modules/@oclif/core/lib/main.js:85:16)",
  "warnings": []
}_

**Comment by tarcang** [comment]
@ViraOsinaCT Would you mind creating a new scratch org in api version 60 using the plugin? Your scratch org may be missing a feature permission. If you want to keep the same scratchorg, check [the scratch definition file we are using](https://github.com/forcedotcom/commerce-on-lightning/blob/develop/config/both-project-scratch-def.json) and compare the features and settings.

**Comment by ViraOsinaCT** [comment]
@tarcang I've created a new scratch org in api 60:
{
  "status": 0,
  "result": {
    "scratchOrgCreated": true
  },
  "warnings": [
    "apiVersion configuration overridden at \"60.0\""
  ]
}

But when I proceed to create a new Store in this org I still get the same error:

{
  "status": 1,
  "name": "SfdxError",
  "message": "{\n    \"code\": 1,\n    \"context\": \"DataSoqlQueryCommand\",\n    \"commandName\": \"DataSoqlQueryCommand\",\n    \"message\": \"The requested resource does not exist\",\n    \"name\": \"NOT_FOUND\",\n    \"status\": 1,\n    \"stack\": \"NOT_FOUND: The requested resource does not exist\\n    at HttpApi.getError (/usr/local/lib/sf/node_modules/jsforce/lib/http-api.js:252:12)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async /usr/local/lib/sf/node_modules/jsforce/lib/http-api.js:122:23\\n    at async Query._execute (/usr/local/lib/sf/node_modules/jsforce/lib/query.js:413:18)\\n    at async /usr/local/lib/sf/node_modules/jsforce/lib/query.js:346:9\",\n    \"exitCode\": 1,\n    \"warnings\": [\n        \"The \\\"-u\\\" flag has been deprecated. Use \\\"--target-org | -o\\\" instead.\",\n        \"The \\\"--apiversion\\\" flag has been deprecated. Use \\\"--api-version\\\" instead.\"\n    ],\n    \"command\": \"sfdx force:data:soql:query -u \\\"test_b2с@test.com\\\" -q \\\"SELECT Type FROM WebStore WHERE Name = 'b2cTestStore'\\\" --json --apiversion=60.0\"\n}",
  "exitCode": 1,
  "commandName": "StoreQuickstartSetup",
  "stack": "SfdxError: {\n    \"code\": 1,\n    \"context\": \"DataSoqlQueryCommand\",\n    \"commandName\": \"DataSoqlQueryCommand\",\n    \"message\": \"The requested resource does not exist\",\n    \"name\": \"NOT_FOUND\",\n    \"status\": 1,\n    \"stack\": \"NOT_FOUND: The requested resource does not exist\\n    at HttpApi.getError (/usr/local/lib/sf/node_modules/jsforce/lib/http-api.js:252:12)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async /usr/local/lib/sf/node_modules/jsforce/lib/http-api.js:122:23\\n    at async Query._execute (/usr/local/lib/sf/node_modules/jsforce/lib/query.js:413:18)\\n    at async /usr/local/lib/sf/node_modules/jsforce/lib/query.js:346:9\",\n    \"exitCode\": 1,\n    \"warnings\": [\n        \"The \\\"-u\\\" flag has been deprecated. Use \\\"--target-org | -o\\\" instead.\",\n        \"The \\\"--apiversion\\\" flag has been deprecated. Use \\\"--api-version\\\" instead.\"\n    ],\n    \"command\": \"sfdx force:data:soql:query -u \\\"test_b2с@test.com\\\" -q \\\"SELECT Type FROM WebStore WHERE Name = 'b2cTestStore'\\\" --json --apiversion=60.0\"\n}\n    at shellJsonSfdx (/Users/viraosina/.local/share/sf/node_modules/@salesforce/commerce/lib/lib/utils/shell.js:111:23)\n    at forceDataSoql (/Users/viraosina/.local/share/sf/node_modules/@salesforce/commerce/lib/lib/utils/sfdx/forceDataSoql.js:19:38)\n    at StoreQuickstartSetup.getStoreType (/Users/viraosina/.local/share/sf/node_modules/@salesforce/commerce/lib/commands/commerce/store/quickstart/setup.js:63:64)\n    at StoreQuickstartSetup.run (/Users/viraosina/.local/share/sf/node_modules/@salesforce/commerce/lib/commands/commerce/store/quickstart/setup.js:85:48)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async StoreQuickstartSetup._run (/Users/viraosina/.local/share/sf/node_modules/@salesforce/command/lib/sfdxCommand.js:81:40)\n    at async StoreCreate.pushStoreSources (/Users/viraosina/.local/share/sf/node_modules/@salesforce/commerce/lib/commands/commerce/store/create.js:259:21)\n    at async StoreCreate.run (/Users/viraosina/.local/share/sf/node_modules/@salesforce/commerce/lib/commands/commerce/store/create.js:180:9)\n    at async StoreCreate._run (/Users/viraosina/.local/share/sf/node_modules/@salesforce/command/lib/sfdxCommand.js:81:40)\n    at async Config.runCommand (/Users/viraosina/.local/share/sf/client/2.23.20-50cd2d8/node_modules/@oclif/core/lib/config/config.js:417:25)",
  "warnings": [
    "apiVersion configuration overridden at \"60.0\""
  ]
}
{
  "status": 1,
  "name": "SfdxError",
  "message": "StoreQuickstartSetup failed",
  "exitCode": 1,
  "commandName": "StoreCreate",
  "stack": "SfdxError: StoreQuickstartSetup failed\n    at StoreCreate.pushStoreSources (/Users/viraosina/.local/share/sf/node_modules/@salesforce/commerce/lib/commands/commerce/store/create.js:261:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async StoreCreate.run (/Users/viraosina/.local/share/sf/node_modules/@salesforce/commerce/lib/commands/commerce/store/create.js:180:9)\n    at async StoreCreate._run (/Users/viraosina/.local/share/sf/node_modules/@salesforce/command/lib/sfdxCommand.js:81:40)\n    at async Config.runCommand (/Users/viraosina/.local/share/sf/client/2.23.20-50cd2d8/node_modules/@oclif/core/lib/config/config.js:417:25)\n    at async run (/Users/viraosina/.local/share/sf/client/2.23.20-50cd2d8/node_modules/@oclif/core/lib/main.js:85:16)",
  "warnings": [
    "apiVersion configuration overridden at \"60.0\""
  ]
}

**Comment by tarcang** [comment]
Can you try using the https://www.npmjs.com/package/@salesforce/commerce/v/248.1.3 version of the plugin? This one doesn't have the source files that have ShippingConfigurationSet. Older scratch orgs need to use the older version of the plugin.
