### ISSUE TITLE
Error with DisplayUserCommand : Nonexistent flag -v

### ISSUE THREAD

**Issue by RaphDuf** [forcedotcom/commerce-on-lightning#318]
Running the sfdx command : 

`sf commerce:store:create -t 'B2B Commerce (LWC)' -n b2bstore01 -o b2b -b b2b_buyer@1commerce.com -u xxxxx@xxxxx.scratch -v DevHub --apiversion=60.0`

after completing 'quickstart step 4', I have this error : 

`Starting import for WebStore ID: 0ZERR000003BEyn4AG to https://force-agility-8409-dev-ed.scratch.my.salesforce.com/services/data/v60.0/commerce/management/import/product/jobs
Importing products.... Done importing products, got results:
{"message":"","status":0,"result":{"attributes":{"type":"ContentVersion","url":"/services/data/v60.0/sobjects/ContentVersion/068RR000002btpBYAQ"},"Id":"068RR000002btpBYAQ","ContentDocumentId":"069RR000002bK3RYAU"},"command":"sfdx shane:data:file:upload -f C:\\Users\\rapha\\.commerce\\examples/csv/Alpine-small.csv -u \"xxxxx@xxxxx.scratch\" --json --apiversion=60.0"}
Mapping Admin User to Role.
User role 'CEO' already exists
ERROR running StoreQuickstartSetup:  {
    "code": 2,
    "context": "DisplayUserCommand",
    "commandName": "DisplayUserCommand",
    "message": "Nonexistent flag: -v\nSee more help with --help",
    "name": "Error",
    "status": 2,
    "stack": "Error: Nonexistent flag: -v\nSee more help with --help\n    at validateArgs (C:\\Users\\rapha\\AppData\\Roaming\\npm\\node_modules\\@salesforce\\cli\\node_modules\\@oclif\\core\\lib\\parser\\validate.js:10:19)\n    at validate (C:\\Users\\rapha\\AppData\\Roaming\\npm\\node_modules\\@salesforce\\cli\\node_modules\\@oclif\\core\\lib\\parser\\validate.js:190:5)\n    at Object.parse (C:\\Users\\rapha\\AppData\\Roaming\\npm\\node_modules\\@salesforce\\cli\\node_modules\\@oclif\\core\\lib\\parser\\index.js:19:35)\n    at async DisplayUserCommand.parse (C:\\Users\\rapha\\AppData\\Roaming\\npm\\node_modules\\@salesforce\\cli\\node_modules\\@oclif\\core\\lib\\command.js:253:25)\n    at async DisplayUserCommand.run (file:///C:/Users/rapha/AppData/Roaming/npm/node_modules/@salesforce/cli/node_modules/@salesforce/plugin-user/lib/commands/org/display/user.js:24:27)\n    at async DisplayUserCommand._run (C:\\Users\\rapha\\AppData\\Roaming\\npm\\node_modules\\@salesforce\\cli\\node_modules\\@oclif\\core\\lib\\command.js:311:22)\n    at async Config.runCommand (C:\\Users\\rapha\\AppData\\Roaming\\npm\\node_modules\\@salesforce\\cli\\node_modules\\@oclif\\core\\lib\\config\\config.js:433:25)\n    at async run (C:\\Users\\rapha\\AppData\\Roaming\\npm\\node_modules\\@salesforce\\cli\\node_modules\\@oclif\\core\\lib\\main.js:92:16)",
    "exitCode": 2,
    "warnings": [],
    "command": "sfdx force:user:display -u \"scratch5@itbrm.scratch\" -v \"duflot@itbrm.sandbox\" --json --apiversion=60.0"
}
ERROR running commerce:store:create:  StoreQuickstartSetup failed`

I use cli 2.44.8 and node 20.14.0, and the lastest version of this git. 
If you have any advice.

**Comment by avaHitesh-github** [comment]
I'm facing the same issue as well!
